### ISSUE TITLE
Update when partitionning the usb drive from el capitan

### ISSUE THREAD

**Issue by jbcordina** [AustinSMU/PRECISION-M3800-OSX#10]
Hi !

Not really an issue but may be intersting for other users on El Capitan.

The disk utility app has changed in El Capitan. It is now impossible to create a partition on a usb drive but the diskutil command is still available from the terminal :

diskutil partitionDisk usb \
2 MBR \
MS-DOS EFI 200M \
HFS+ install_osx R

usb is the usb drive name
MS-DOS = FAT32
200M = size for the MS-DOS partition
R = rest of the volume space

**Comment by AustinSMU** [comment]
Why would you even post this here? It isn't interesting because it's an update to the OS - there's no need to point out the obvious.
1. It has nothing to do with my project.
2. The only change was to the GUI, not the underlying functionality, as Disk Utilty is just a frontend for the diskutil command.
3. You claim it's impossible, yet follow with a very obvious explanation.
4. Executing "defaults write com.apple.DiskUtility advanced-image-options 1" (without quotes) via command line will enable the missing GUI functions.
